---
- name: Generate crio.conf
  template:
    src: crio.conf.j2
    dest: "{{ crio_conf_file }}"
    owner: root
    group: root
    mode: "0644"
  when: crio_conf is defined
  become: true

- name: Ensure CRI-O is started and enabled at boot
  systemd:
    name: crio
    enabled: true
    state: started
  become: true
