---
- include_tasks: "variables.yml"
  tags:
    - always
- include_tasks: "modprobe.yml"
- include_tasks: "kernel_parameters.yml"
- include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "setup-{{ ansible_os_family }}.yml"
- include_tasks: "configure.yml"
