---
- name: Load kernel modules.
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ crio_modules }}"
  become: true
  tags:
    - molecule-notest

- name: Persistent kernel module loading.
  template:
    src: crio-modules.conf.j2
    dest: "{{ crio_modprobe_filename }}"
    owner: root
    group: root
    mode: "0644"
  become: true
