---
- name: Force apt update at Debian
  apt:
    update_cache: true
  become: true
  when: crio_apt_force_update

- name: Ensure gpg-agent is installed for the apt_key module
  apt:
    name: "{{ crio_gpg_packages }}"
    cache_valid_time: "{{ crio_apt_cache_valid_time }}"
    update_cache: "{{ crio_apt_update_cache }}"
    state: present
  become: true

- name: Add an apt key of cri-o utils
  apt_key:
    url: "{{ crio_apt_repo_key_url }}"
    state: present
  become: true

- name: Add an apt repository of cri-o utils
  apt_repository:
    repo: "{{ crio_apt_repo }}"
    filename: "{{ crio_apt_repo_filename }}"
    state: present
  become: true

- name: Add an apt key of cri-o
  apt_key:
    url: "{{ crio_apt_crio_repo_key_url }}"
    state: present
  become: true

- name: Add an apt repository of cri-o
  apt_repository:
    repo: "{{ crio_apt_crio_repo }}"
    filename: "{{ crio_apt_crio_repo_filename }}"
    state: present
  become: true

- name: Install cri-o
  apt:
    name:
      - "cri-o={{ crio_install_version }}"
      - "cri-o-runc{{ '=' ~ crio_runc_version if crio_runc_version is defined else '' }}"
    default_release: "{{ crio_apt_backports_name if crio_apt_backports_repo_enable else omit }}"
    state: present
  become: true
