---
- name: Include OS-specfic variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution }}-{{ ansible_lsb.release | default('') }}.yml"
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
      skip: true
  tags:
    - always

- name: Define crio_os
  set_fact:
    crio_os: "{{ __crio_os }}"
  when: crio_os is not defined

- name: Define crio_install_version
  set_fact:
    crio_install_version: "{{ crio_version ~ '~*' if crio_version.split('.') | length > 2 else crio_version ~ '.*' }}"
  when: crio_install_version is not defined

- name: Define crio_long_version
  set_fact:
    crio_long_version: "{{ crio_version.split('.')[0:2] | join('.') ~ ':' ~ crio_version if crio_version.split('.') | length > 2 else crio_version }}"  # yamllint disable-line rule:line-length
  when: crio_long_version is not defined

- name: Define crio_version_url
  set_fact:
    crio_version_url: "{{ crio_version.split('.')[0:2] | join('.') ~ ':/' ~ crio_version if crio_version.split('.') | length > 2 else crio_version }}"  # yamllint disable-line rule:line-length
  when: crio_version_url is not defined

- name: Define crio_apt_backports_repo_enable
  set_fact:
    crio_apt_backports_repo_enable: "{{ __crio_apt_backports_repo_enable | default(false) }}"
  when: crio_apt_backports_repo_enable is not defined

- name: Define crio_backports_packages
  set_fact:
    crio_backports_packages: "{{ __crio_backports_packages | default([]) }}"
  when: crio_backports_packages is not defined
