---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    privileged: true
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
      # Specify according to the parameters in /etc/containers/storage.conf.
      - /run/containers/storage  # runroot
      - /var/lib/containers/storage  # graphroot
    cgroupns_mode: host
    groups:
      - ${MOLECULE_DISTRO:-ubuntu2004}
provisioner:
  name: ansible
  options:
    diff: true
  inventory:
    group_vars:
      all: {}
      debian10:
        cache_valid_time: 0
      debian11:
        cache_valid_time: 0
      ubuntu2204:
        ansible_remote_tmp: /tmp
verifier:
  name: ansible
