---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache for Debian-based systems
      raw: apt-get update
      when: >
        inventory_hostname in groups.get('debian10', []) or
        inventory_hostname in groups.get('debian11', []) or
        inventory_hostname in groups.get('debian12', []) or
        inventory_hostname in groups.get('ubuntu2004', []) or
        inventory_hostname in groups.get('ubuntu2204', [])
      changed_when: false

    - name: Preparation completed
      raw: echo "Preparation completed"
      changed_when: false
