---
- name: Prepare tasks
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure /etc/modules-load.d directory is exists
      ansible.builtin.file:
        path: /etc/modules-load.d
        state: directory
    - name: Ensure /etc/sysctl.d directory is exists
      ansible.builtin.file:
        path: /etc/sysctl.d
        state: directory
    - name: Ensure /usr/share/man/man1/ is exists
      ansible.builtin.file:
        name: /usr/share/man/man1/
        recurse: true
        state: directory
    - name: Execute systemctl daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
    - name: Ensure can access to Internet
      ansible.builtin.command: "ping -c google.com"
    - name: 
      ansible.builtin.command: "cat /etc/resolv.conf"
      ignore_errors: true
      register: resolv_conf
    - name: 
      ansible.builtin.debug:
        msg: "{{ resolv_conf.stdout }}"
        #- name: Prepare tasks
        #  hosts: rockylinux9
        #  gather_facts: false
        #  tasks:
        #    - name: Set resolv.conf
        #      ansible.builtin.copy:
        #        dest: /etc/resolv.conf
        #        content: |
        #          nameserver 8.8.8.8
        #          nameserver 8.8.4.4
        #        owner: root
        #        group: root
        #        mode: "0644"
