---
name: CI
'on':
  pull_request:
  push:
    branches:
      - "*"

defaults:
  run:
    working-directory: 'ktooi.crio'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ktooi.crio'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache packages
        uses: actions/cache@v3
        env:
          cache-name: python-3
        with:
          path: ~/.cache/pip
          key: ktooi-crio-yamllint

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos7
          - centos8
          - ubuntu2204
          - ubuntu2110
          - ubuntu2104
          - ubuntu2010
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ktooi.crio'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache packages
        uses: actions/cache@v3
        env:
          cache-name: python-3
        with:
          path: |
            ~/.cache/pip
            ansible_collections/
            build/
            /opt/hostedtoolcache/Python/
          key: ktooi-crio-molecule

      - name: Install test dependencies.
        run: pip3 -vvv install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
